# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:55
from __future__ import unicode_literals

import apps.login.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170224_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(max_length=55, validators=[apps.login.models.validateLengthGreaterThanTwo, django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='Must be letters only.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=55, validators=[apps.login.models.validateLengthGreaterThanTwo, django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='Must be letters only.')]),
        ),
    ]
