# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20170224_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
